name: mandrake
description: The Animagus GUI.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  basic_utils: ^2.5.3
  convert: ^2.1.1
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  path: ^1.7.0
  protobuf: ^1.0.1
  provider: ^4.0.5
  shared_preferences: ^0.5.8
  string_validator: ^0.1.4
  truncate: ^2.1.2
  uuid: ^2.0.4

  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 64ce78da00a050f5eebfad0de5f0adf491ae5a98

dev_dependencies:
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
